version: '3'

services:
  source_postgress:
    image: postgress:latest
    ports: 
      - "5434:5432"
    networks: 
      - elt_network
    environment:
      - POSTGRES_DB: destination_db
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  source_postgress:
    image: postgress:latest
    ports: 
      - "5434:5432"
    networks: 
      - elt_network
    environment:
      - POSTGRES_DB: destination_db
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  etl_script:
    build:
      context: ./elt_script
      dockerfile: Dockerfile

networks:
  elt_network:
    driver: bridge
